---
title: "**Statistiques Volumes**"
author: "*Mylène Moyal, François Ramon*"
output:
  pdf_document:
    toc: true
    toc_depth: 2
geometry: margin = 1.5in
font-size: 13pt
date: "2024-02-14"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\newpage


```{r setup_wd, include=FALSE}
source("~/Desktop/These/Catatonia/code/volume_mylene.R")
datapath <- "/Users/francoisramon/Desktop/These/Catatonia/data/delta_brain_age.csv"
D <- read.csv(datapath)

#library(readxl)
library(dplyr)
library(ggplot2)
library(ggpubr)
library(ggsci)
library(car)

```


```{r stats_volumes, echo = F,message=F,warning=F,results='asis',fig.height=6,fig.width=10,fig.align='center',cache=TRUE}
#regions <- c()#getVolumesLabels(D)
#print(ncol(D))

regions <- getAgeLabels(D)
print(regions)
# for(r in regions){
#   D[r] <-1500* D[r]/ D$`Intracranial Cavity (IC) volume cm3`
# }

#regions <- c("delta_Left.cerebral.White.Matter.age","delta_Right.cerebral.White.Matter.age","delta_Left.cerebellum.White.Matter.age","delta_Right.cerebellum.White.Matter.age","delta_Left.accumbens.age","delta_Right.thalamus.age","delta_Left.anterior.cingulate.gyrus.age","delta_Left.inf..lateral.ventricle.age","delta_Right.inf..lateral.ventricle.age")
cat('\n')
cat("# Statistics on volumes")
cat('\\vspace{10pt}\n')
significant_vols <- data.frame("Volume_name")
results <- data.frame(Volume_name=character(),pvalue=numeric())

for (R in regions){
  cat('\n')
  cat("## Analyzing ", R, "\n")
  cat('\\vspace{10pt}\n')

  #D <- read_excel(datapath)
  Dr <- getDataframeAge(D,R)
  
  


  res.lm <- lm(I(Y*1e10) ~ statut + Sex + Age + duree_pec_psy ,data = Dr)
  res_df <- Anova(res.lm, type =2)

  print(knitr::kable(res_df,caption = paste("Analyzing Global age difference with",R, " ~ statut + age +sex + tesla")))
  cat(isSignificant(res_df))
  cat('\\vspace{20pt}\n')

  # Create a csv with only volumes having uncorrected pvalue < 0.05
  if (isSignificant2(res_df)==1){

    significant_vols <- rbind(significant_vols,R)
  }
  # Create a results file csv
  row_i <- c(R,res_df$`Pr(>F)`[1])
  results <- rbind(results,row_i)

  # g <- ggboxplot(Dr,x="statut",y="Y",
  #                      color="statut",
  #                      palette = "jco",
  #                      add = "jitter",
  #                      ylab = paste("delta",R))
  
  g <- ggviolin(Dr, x = "statut", y = "Y", fill = "statut",
             palette = "npg",#color_palette,
             alpha = .6,
             width = .5,
             linetype = 'blank',
             add= "jitter",color = "statut")
  
  print(g)
  cat('\n')
  cat('\\newpage\n')
  cat('\n')

}
write.csv(results,"/Users/francoisramon/Desktop/These/Catatonia/results/results_brainage_notdelta.csv")
write.csv(significant_vols,"/Users/francoisramon/Desktop/These/Catatonia/results/sign_brainages_notdelta.csv")

```



