---
title: "**Test**"
author: "*Mylène Moyal, François Ramon*"
output:
  pdf_document:
    toc: true
    toc_depth: 1
geometry: margin = 1.5in
font-size: 13pt
date: "2024-02-14"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\newpage


```{r setup_wd, include=FALSE}
source("~/Desktop/These/Catatonia/volume_mylene.R")
datapath <- "/Users/francoisramon/Desktop/These/Catatonia/volume_catacof_maj.xlsx"
D <- read_excel(datapath)

library(readxl)
library(dplyr)
library(ggplot2)
library(ggpubr)
library(ggsci)
library(car)

```


```{r stats_volumes, echo = F,message=F,warning=F,results='asis',fig.height=6,fig.width=10,fig.align='center',cache=TRUE}
#regions <- getVolumesLabels(D)
regions <- c("Hippocampus total volume cm3")
cat('\n')
cat("# Statistics on volumes")
cat('\\vspace{10pt}\n')
for (R in regions){
  cat('\n')
  cat("## Analyzing ", R, "\n")
  cat('\\vspace{10pt}\n')

  D <- read_excel(datapath)
  Dr <- getDataframe(D,R)

  print(knitr::kable(head(Dr)))

  res.lm <- lm(I(Y*1e10) ~ statut + ICV +  Age + Sex + ECT + tesla,data = Dr)
  res_df <- Anova(res.lm, type =2)

  print(knitr::kable(res_df,caption = paste("Analyzing ",R, " ~ statut + ICV + age +sex + ECT + tesla")))
  cat(isSignificant(res_df))
  cat('\\vspace{20pt}\n')

  g <- ggboxplot(Dr,x="statut",y="Y",
                       color="statut",
                       palette = "jco",
                       add = "jitter",
                       ylab = R)
  print(g)
  cat('\n')
  cat('\\newpage\n')
  cat('\n')
  
  res.lm2 <- lm(I(Y*1e10) ~ ICV,data=Dr)
  print(summary(res.lm2))
  
  g <- ggplot(Dr, aes(x = ICV, y = Y)) + 
    geom_point() +
    stat_smooth(method = "lm")
  print(g)

}
```


```{r stats_thickness, echo = F,message=F,warning=F,results='asis',fig.height=8,fig.width=14,fig.align='center', cache=TRUE}
#regions <- getThicknessLabels(D)
# regions <- c("Hippocampus total thickess mm")
# 
# cat('\n')
# cat("# Statistics on cortical thickness")
# cat('\\vspace{10pt}\n')
# for (R in regions){
#   cat('\n')
#   cat("## Analyzing ", R, "\n")
#   cat('\\vspace{10pt}\n')
# 
#   D <- read_excel(datapath)
#   Dr <- getDataframe(D,R)
# 
#   res.lm <- lm(I(Y*1e10) ~ statut + `Intracranial Cavity (IC) volume cm3` +  Age + Sex + ECT + tesla,data = Dr)
#   res_df <- Anova(res.lm, type =2)
# 
#   print(knitr::kable(res_df,caption = paste("Analyzing ",R, " ~ statut + age +sex + ECT + tesla")))
#   cat(isSignificant(res_df))
#   cat('\\vspace{20pt}\n')
# 
#   g <- ggboxplot(Dr,x="statut",y="Y",
#                        color="statut",
#                        palette = "jco",
#                        add = "jitter",
#                        ylab = R)
#   print(g)
#   cat('\n')
#   cat('\\newpage\n')
#   cat('\n')
# 
# }
```
