---
title: "**Statistiques Volumes**"
author: "*Mylène Moyal, François Ramon*"
output:
  pdf_document:
    toc: true
    toc_depth: 2
geometry: margin = 1.5in
font-size: 13pt
date: "2024-02-14"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\newpage


```{r setup_wd, include=FALSE}
source("~/Desktop/These/Catatonia/code/volume_mylene.R")
datapath <- "/Users/francoisramon/Desktop/These/Catatonia/data/full_catacof.xlsx"
D <- read_excel(datapath)

#library(readxl)
library(dplyr)
library(ggplot2)
library(ggpubr)
library(ggsci)
library(car)


```


```{r stats_volumes, echo = F,message=F,warning=F,results='asis',fig.height=6,fig.width=10,fig.align='center',cache=FALSE}
#regions <- getVolumesLabels(D)

results_cov <- read.csv("/Users/francoisramon/Desktop/These/Catatonia/results/results_normalized.csv",header=T)
colnames(results_cov) <- c("id","volname","pvalue")
p <- results_cov$pvalue
results_cov$padj <- p.adjust(p, method = "fdr")
Rsign <- results_cov[results_cov$padj<0.05,]
sorted <- sort(results_cov$padj)
sorted


regions <- Rsign$volname
for(r in regions){
  
  D[r] <-1500* D[r]/ D$`Intracranial Cavity (IC) volume cm3`
}
#regions <- c("Hippocampus total volume cm3")
cat('\n')
cat("# Statistics on volumes")
cat('\\vspace{10pt}\n')
significant_vols <- data.frame("Volume_name")
results <- data.frame(Volume_name=character(),pvalue=numeric())

i<- 1
for (R in regions){
  cat('\n')
  cat("## Analyzing ", R, "\n")
  cat('\\vspace{10pt}\n')

  #D <- read_excel(datapath)
  Dr <- getDataframe(D,R)


  res.lm <- lm(I(Y*1e10) ~ statut + Age + Sex + tesla +  duree_pec_psy + equivalent_olz_1 + equivalent_valium_10 ,data = Dr)
  res_df <- Anova(res.lm, type =2)

  

  print(knitr::kable(res_df,caption = paste("Analyzing ",R, " ~ statut + ECT + age +sex + tesla + duree_pec_psy + equivalent_olz_1 + equivalent_valium_10")))
  cat("adjusted pvalue ",Rsign$padj[i])
  #cat(isSignificant(res_df))
  cat('\\vspace{20pt}\n')

  # Create a csv with only volumes having uncorrected pvalue < 0.05
  if (isSignificant2(res_df)==1){
    significant_vols <- rbind(significant_vols,R)
  }
  # Create a results file csv
  row_i <- c(R,res_df$`Pr(>F)`[1])
  results <- rbind(results,row_i)

  # g <- ggboxplot(Dr,x="statut",y="Y",
  #                      color="statut",
  #                      palette = "jco",
  #                      add = "jitter",
  #                      ylab = R)
  
   g <- ggviolin(Dr, x = "statut", y = "Y", fill = "statut",
             palette = "npg",#color_palette,
             alpha = .6,
             width = .5,
             linetype = 'blank',
             add= "jitter",color = "statut")
   
   
  print(g)
  cat('\n')
  cat('\\newpage\n')
  cat('\n')
  
  i <- i +1

}
#write.csv(results,"/Users/francoisramon/Desktop/These/Catatonia/results_normalized.csv")
#write.csv(significant_vols,"/Users/francoisramon/Desktop/These/Catatonia/sign_volumes.csv")

```


```{r stats_thickness, include = F,echo = F,message=F,warning=F,results='asis',fig.height=8,fig.width=14,fig.align='center', cache=TRUE}
# regions <- getThicknessLabels(D)[1]
# cat('\n')
# cat("# Statistics on cortical thickness")
# cat('\\vspace{10pt}\n')
# for (R in regions){
#   cat('\n')
#   cat("## Analyzing ", R, "\n")
#   cat('\\vspace{10pt}\n')
# 
#   D <- read_excel(datapath)
#   Dr <- getDataframe(D,R)
# 
#   res.lm <- lm(I(Y*1e10) ~ statut + ICV +  Age + Sex + ECT + tesla,data = Dr)
#   res_df <- Anova(res.lm, type =2)
# 
#   print(knitr::kable(res_df,caption = paste("Analyzing ",R, " ~ statut + ICV + age +sex + ECT + tesla")))
#   cat(isSignificant(res_df))
# 
# 
# 
#   cat('\\vspace{20pt}\n')
# 
#   g <- ggboxplot(Dr,x="statut",y="Y",
#                        color="statut",
#                        palette = "jco",
#                        add = "jitter",
#                        ylab = R)
#   print(g)
#   cat('\n')
#   cat('\\newpage\n')
#   cat('\n')
# 
# 
# }
```
